Feature/itrex 495 authzlib
IT-REX-Platform/CourseService pull request #22
Opened 2021-02-26 10:58 UTC by acraea-x

2021-02-26 11:18 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> +
Remove new line

2021-02-26 11:18 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> + * further details tbd
open todo?

2021-02-26 11:48 UTC, Well5a requested changes
Please run checkstyle, I get 112 errors in RexAuthz

Also it would be great if we had at least some tests for helper functions in RexAuthz

2021-02-26 11:48 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> + * further details tbd
open todo?

2021-02-26 11:48 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> +
remove new line

2021-02-26 11:48 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> +    }
Wieso keine Funktion für UserIsCourseManager?

2021-02-26 11:48 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> +    public enum RexRole {
move enums to their own class in domain/enumeration

2021-02-26 11:48 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/course/web/rest/written/RexAuthzCheckResource.java
> +public class RexAuthzCheckResource {
please dont merge this file, we don't want to add an endpoint that is not used

2021-02-26 11:49 UTC, acraea-x commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> + * further details tbd
removed

2021-02-26 11:50 UTC, acraea-x commented on src/main/java/de/uni_stuttgart/it_rex/course/service/written/RexAuthz.java
> +
ok

2021-02-26 16:09 UTC, Well5a submitted a review, later dismissed

2021-02-26 16:09 UTC, Well5a commented
fixed things I complained about, please review again.

2021-02-27 12:10 UTC, Noeliel approved these changes

2021-03-01 14:34 UTC, DasGraMMa approved these changes

2021-03-01 14:36 UTC, merged